Repository AdobeDocs/commerce-testing, pull requests merged in 2022-10, with the labels that each got.

#25 COMDOX-346: Restore workflow customizations
  .env.example
  .github/dependabot.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  CODE_OF_CONDUCT.md
  package.json
  yarn.lock
Labels: enhancement

#20 ACP2E-1186: Document the 'count' and 'scope' introduction
  src/pages/guide/integration/attributes/data-fixture-before-transaction.md
  src/pages/guide/integration/attributes/data-fixture.md
Labels: major update

#26 Bumped aio-theme
  package.json
  yarn.lock
Labels: dependencies

#27 Update theme, link checker, yarn
  .github/workflows/test-pull-request.yml
  .yarn/releases/yarn-3.2.2.cjs
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: bug, dependencies
