Repository AdobeDocs/commerce-testing, pull requests merged in 2023-10, with the labels that each got.

#59 Update app-area.md
  src/pages/guide/integration/attributes/app-area.md
Labels: editorial

#67 ACQE-5463: Document AllowList for TestDependency
  src/pages/functional-testing-framework/commands/mftf.md
Labels: major update, internal

#68 Rename the test:links task
  package.json
Labels: enhancement, maintenance
