Repository AdobeDocs/commerce-testing, pull requests merged in 2023-11, with the labels that each got.

#69 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#70 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#71 Adjust grammar in writing-testable-code.md
  src/pages/guide/unit/writing-testable-code.md
Labels: editorial

#73 Sync configs with other projects
  .remarkrc.mjs
  package.json
Labels: maintenance

#74 Add validation for custom headers
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: bug, enhancement

#75 Update theme and caniuse-lite
  package.json
  yarn.lock
Labels: dependencies

#63 COMDOX-775: Update the Metadata documentation in mftf dev docs
  src/pages/functional-testing-framework/metadata.md
Labels: major update, internal
