Repository AdobeDocs/commerce-testing, pull requests merged in 2023-05, with the labels that each got.

#49 Add autodeployment
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: enhancement

#51 Convert add-to-project-board to reusable workflow
  .github/workflows/add-to-project-board.yml
Labels: enhancement, maintenance

#52 Fix typo in magento-cache.md
  src/pages/guide/integration/annotations/magento-cache.md
Labels: editorial
