Repository AdobeDocs/commerce-testing, pull requests merged in 2024-06, with the labels that each got.

#96 Upgrade theme to v4.11.14
  package.json
  yarn.lock
Labels: dependencies, internal

#98 AC-12309::Update user documentation for two-factor authentication (2F…
  src/pages/functional-testing-framework/two-factor-authentication.md
Labels: editorial, internal

#99 [ImgBot] Optimize images
  src/pages/_images/functional-testing/action-groups-dia.svg
  src/pages/_images/functional-testing/data-dia.svg
  src/pages/_images/functional-testing/metadata-dia.svg
  src/pages/_images/functional-testing/mftf-extending-precedence.png
  src/pages/_images/functional-testing/page-dia.svg
  src/pages/_images/functional-testing/section-dia.svg
  src/pages/_images/functional-testing/test-dia.svg
Labels: editorial
