Repository AdobeDocs/commerce-testing, pull requests merged in 2024-04, with the labels that each got.

#87 Upgrade theme to v4.11.9
  package.json
  yarn.lock
Labels: dependencies, internal

#90 April 2024 release (2.4.7 GA)
  src/pages/functional-testing-framework/two-factor-authentication.md
Labels: 2.4.7

#91 Update two-factor-authentication.md to match new requirement for otp_…
  src/pages/functional-testing-framework/two-factor-authentication.md
Labels: dependencies
