Repository AdobeDocs/commerce-testing, pull requests merged in 2025-02, with the labels that each got.

#135 ACP2E-3062: Documentation and static test of standard integration test fixture
  src/pages/guide/integration/attributes/data-fixture.md
Labels: major-update, internal

#138 Upgrade actions/cache in the GitHub workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#139 Update GH Pages workflow
  .github/workflows/github-pages.yml
Labels: maintenance, internal

#140 Update GH pages workflows according to the GH sample
  .github/workflows/deploy-to-pages.yml
  .github/workflows/github-pages.yml
Labels: maintenance

#141 Delete duplicate workflow
  .github/workflows/deploy-to-pages.yml
Labels: maintenance

#143 fix: path to allure report output
  src/pages/functional-testing-framework/getting-started.md
Labels: internal, technical
